-- STASIS PostgreSQL bootstrap script
-- Run with:
--   psql -U stasis_app -d stasis -f STASIS/STASIS_create_tables_postgres.sql

BEGIN;

-- Drop STASIS tables first, then ASP.NET Identity tables.
DROP TABLE IF EXISTS "tbl_AuditLog" CASCADE;
DROP TABLE IF EXISTS "tbl_FilterPaperUsages" CASCADE;
DROP TABLE IF EXISTS "tbl_ShipmentContents" CASCADE;
DROP TABLE IF EXISTS "tbl_Shipments" CASCADE;
DROP TABLE IF EXISTS "tbl_ShipmentRequests" CASCADE;
DROP TABLE IF EXISTS "tbl_ShipmentBatches" CASCADE;
DROP TABLE IF EXISTS "tbl_Specimens" CASCADE;
DROP TABLE IF EXISTS "tbl_Approvals" CASCADE;
DROP TABLE IF EXISTS "tbl_SampleTypes" CASCADE;
DROP TABLE IF EXISTS "tbl_Studies" CASCADE;
DROP TABLE IF EXISTS "tbl_Boxes" CASCADE;
DROP TABLE IF EXISTS "tbl_Racks" CASCADE;
DROP TABLE IF EXISTS "tbl_Freezers" CASCADE;
DROP TABLE IF EXISTS "tbl_UserProfiles" CASCADE;

DROP TABLE IF EXISTS "AspNetUserTokens" CASCADE;
DROP TABLE IF EXISTS "AspNetUserLogins" CASCADE;
DROP TABLE IF EXISTS "AspNetUserClaims" CASCADE;
DROP TABLE IF EXISTS "AspNetRoleClaims" CASCADE;
DROP TABLE IF EXISTS "AspNetUserRoles" CASCADE;
DROP TABLE IF EXISTS "AspNetRoles" CASCADE;
DROP TABLE IF EXISTS "AspNetUsers" CASCADE;

-- ASP.NET Identity tables
CREATE TABLE "AspNetUsers" (
    "Id" varchar(450) NOT NULL,
    "UserName" varchar(256),
    "NormalizedUserName" varchar(256),
    "Email" varchar(256),
    "NormalizedEmail" varchar(256),
    "EmailConfirmed" boolean NOT NULL DEFAULT false,
    "PasswordHash" text,
    "SecurityStamp" text,
    "ConcurrencyStamp" text,
    "PhoneNumber" text,
    "PhoneNumberConfirmed" boolean NOT NULL DEFAULT false,
    "TwoFactorEnabled" boolean NOT NULL DEFAULT false,
    "LockoutEnd" timestamptz,
    "LockoutEnabled" boolean NOT NULL DEFAULT false,
    "AccessFailedCount" integer NOT NULL DEFAULT 0,
    CONSTRAINT "PK_AspNetUsers" PRIMARY KEY ("Id")
);

CREATE INDEX "EmailIndex" ON "AspNetUsers" ("NormalizedEmail");
CREATE UNIQUE INDEX "UserNameIndex" ON "AspNetUsers" ("NormalizedUserName")
WHERE "NormalizedUserName" IS NOT NULL;

CREATE TABLE "AspNetRoles" (
    "Id" varchar(450) NOT NULL,
    "Name" varchar(256),
    "NormalizedName" varchar(256),
    "ConcurrencyStamp" text,
    CONSTRAINT "PK_AspNetRoles" PRIMARY KEY ("Id")
);

CREATE UNIQUE INDEX "RoleNameIndex" ON "AspNetRoles" ("NormalizedName")
WHERE "NormalizedName" IS NOT NULL;

CREATE TABLE "AspNetUserRoles" (
    "UserId" varchar(450) NOT NULL,
    "RoleId" varchar(450) NOT NULL,
    CONSTRAINT "PK_AspNetUserRoles" PRIMARY KEY ("UserId", "RoleId"),
    CONSTRAINT "FK_AspNetUserRoles_AspNetUsers_UserId"
        FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_AspNetUserRoles_AspNetRoles_RoleId"
        FOREIGN KEY ("RoleId") REFERENCES "AspNetRoles" ("Id") ON DELETE CASCADE
);

CREATE INDEX "IX_AspNetUserRoles_RoleId" ON "AspNetUserRoles" ("RoleId");

CREATE TABLE "AspNetUserClaims" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "UserId" varchar(450) NOT NULL,
    "ClaimType" text,
    "ClaimValue" text,
    CONSTRAINT "PK_AspNetUserClaims" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_AspNetUserClaims_AspNetUsers_UserId"
        FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);

CREATE INDEX "IX_AspNetUserClaims_UserId" ON "AspNetUserClaims" ("UserId");

CREATE TABLE "AspNetRoleClaims" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "RoleId" varchar(450) NOT NULL,
    "ClaimType" text,
    "ClaimValue" text,
    CONSTRAINT "PK_AspNetRoleClaims" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_AspNetRoleClaims_AspNetRoles_RoleId"
        FOREIGN KEY ("RoleId") REFERENCES "AspNetRoles" ("Id") ON DELETE CASCADE
);

CREATE INDEX "IX_AspNetRoleClaims_RoleId" ON "AspNetRoleClaims" ("RoleId");

CREATE TABLE "AspNetUserLogins" (
    "LoginProvider" varchar(450) NOT NULL,
    "ProviderKey" varchar(450) NOT NULL,
    "ProviderDisplayName" text,
    "UserId" varchar(450) NOT NULL,
    CONSTRAINT "PK_AspNetUserLogins" PRIMARY KEY ("LoginProvider", "ProviderKey"),
    CONSTRAINT "FK_AspNetUserLogins_AspNetUsers_UserId"
        FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);

CREATE INDEX "IX_AspNetUserLogins_UserId" ON "AspNetUserLogins" ("UserId");

CREATE TABLE "AspNetUserTokens" (
    "UserId" varchar(450) NOT NULL,
    "LoginProvider" varchar(450) NOT NULL,
    "Name" varchar(450) NOT NULL,
    "Value" text,
    CONSTRAINT "PK_AspNetUserTokens" PRIMARY KEY ("UserId", "LoginProvider", "Name"),
    CONSTRAINT "FK_AspNetUserTokens_AspNetUsers_UserId"
        FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);

-- STASIS tables
CREATE TABLE "tbl_UserProfiles" (
    "UserProfileID" integer GENERATED BY DEFAULT AS IDENTITY,
    "AspNetUserId" varchar(450) NOT NULL,
    "Department" varchar(100),
    "CanApproveShipments" boolean NOT NULL DEFAULT false,
    "CanApproveDiscards" boolean NOT NULL DEFAULT false,
    "MustChangePassword" boolean NOT NULL DEFAULT false,
    CONSTRAINT "PK_UserProfiles" PRIMARY KEY ("UserProfileID"),
    CONSTRAINT "UQ_UserProfiles_AspNetUserId" UNIQUE ("AspNetUserId"),
    CONSTRAINT "FK_UserProfiles_AspNetUsers"
        FOREIGN KEY ("AspNetUserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);

CREATE TABLE "tbl_Freezers" (
    "FreezerID" integer GENERATED BY DEFAULT AS IDENTITY,
    "FreezerName" varchar(50) NOT NULL,
    "Temperature" integer,
    "LocationInBuilding" varchar(100),
    CONSTRAINT "PK_Freezers" PRIMARY KEY ("FreezerID"),
    CONSTRAINT "UQ_Freezers_FreezerName" UNIQUE ("FreezerName")
);

CREATE TABLE "tbl_Racks" (
    "RackID" integer GENERATED BY DEFAULT AS IDENTITY,
    "RackName" varchar(50) NOT NULL,
    "FreezerID" integer,
    CONSTRAINT "PK_Racks" PRIMARY KEY ("RackID"),
    CONSTRAINT "FK_Racks_Freezers"
        FOREIGN KEY ("FreezerID") REFERENCES "tbl_Freezers" ("FreezerID") ON DELETE RESTRICT
);

CREATE TABLE "tbl_Boxes" (
    "BoxID" integer GENERATED BY DEFAULT AS IDENTITY,
    "BoxLabel" varchar(50) NOT NULL,
    "BoxType" varchar(50) NOT NULL,
    "BoxCategory" varchar(50) NOT NULL DEFAULT 'Standard',
    "RackID" integer,
    CONSTRAINT "PK_Boxes" PRIMARY KEY ("BoxID"),
    CONSTRAINT "UQ_Boxes_BoxLabel" UNIQUE ("BoxLabel"),
    CONSTRAINT "CK_Boxes_BoxType" CHECK (
        "BoxType" IN ('81-slot', '100-slot', 'Filter Paper Binder')
    ),
    CONSTRAINT "CK_Boxes_BoxCategory" CHECK (
        "BoxCategory" IN ('Standard', 'Temp', 'Trash', 'Shipping')
    ),
    CONSTRAINT "FK_Boxes_Racks"
        FOREIGN KEY ("RackID") REFERENCES "tbl_Racks" ("RackID") ON DELETE RESTRICT
);

CREATE TABLE "tbl_Studies" (
    "StudyID" integer GENERATED BY DEFAULT AS IDENTITY,
    "StudyCode" varchar(50) NOT NULL,
    "StudyName" varchar(200),
    "PrincipalInvestigator" varchar(100),
    CONSTRAINT "PK_Studies" PRIMARY KEY ("StudyID"),
    CONSTRAINT "UQ_Studies_StudyCode" UNIQUE ("StudyCode")
);

CREATE TABLE "tbl_SampleTypes" (
    "SampleTypeID" integer GENERATED BY DEFAULT AS IDENTITY,
    "TypeName" varchar(50) NOT NULL,
    "IsConsumable" boolean NOT NULL DEFAULT false,
    "MaxShippableUnits" integer,
    "LocalReserveUnits" integer,
    CONSTRAINT "PK_SampleTypes" PRIMARY KEY ("SampleTypeID"),
    CONSTRAINT "UQ_SampleTypes_TypeName" UNIQUE ("TypeName")
);

CREATE TABLE "tbl_Approvals" (
    "ApprovalID" integer GENERATED BY DEFAULT AS IDENTITY,
    "ApprovalType" varchar(50) NOT NULL DEFAULT 'Shipment',
    "RequestedByUserId" varchar(450),
    "RequestedDate" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "EDApproverUserId" varchar(450),
    "EDApprovalDate" timestamp,
    "EDApprovalStatus" varchar(20),
    "EDComments" varchar(500),
    "RegulatoryApproverUserId" varchar(450),
    "RegulatoryApprovalDate" timestamp,
    "RegulatoryApprovalStatus" varchar(20),
    "RegulatoryComments" varchar(500),
    "PIApproverUserId" varchar(450),
    "PIApprovalDate" timestamp,
    "PIApprovalStatus" varchar(20),
    "PIComments" varchar(500),
    "OverallStatus" varchar(20) NOT NULL DEFAULT 'Pending',
    CONSTRAINT "PK_Approvals" PRIMARY KEY ("ApprovalID"),
    CONSTRAINT "CK_Approvals_ApprovalType" CHECK (
        "ApprovalType" IN ('Shipment', 'Discard', 'SingleAliquotException')
    ),
    CONSTRAINT "CK_Approvals_EDApprovalStatus" CHECK (
        "EDApprovalStatus" IS NULL OR "EDApprovalStatus" IN ('Pending', 'Approved', 'Rejected')
    ),
    CONSTRAINT "CK_Approvals_RegulatoryApprovalStatus" CHECK (
        "RegulatoryApprovalStatus" IS NULL OR "RegulatoryApprovalStatus" IN ('Pending', 'Approved', 'Rejected')
    ),
    CONSTRAINT "CK_Approvals_PIApprovalStatus" CHECK (
        "PIApprovalStatus" IS NULL OR "PIApprovalStatus" IN ('Pending', 'Approved', 'Rejected')
    ),
    CONSTRAINT "CK_Approvals_OverallStatus" CHECK (
        "OverallStatus" IN ('Pending', 'Approved', 'Rejected')
    ),
    CONSTRAINT "FK_Approvals_RequestedBy"
        FOREIGN KEY ("RequestedByUserId") REFERENCES "AspNetUsers" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_Approvals_EDApprover"
        FOREIGN KEY ("EDApproverUserId") REFERENCES "AspNetUsers" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_Approvals_RegulatoryApprover"
        FOREIGN KEY ("RegulatoryApproverUserId") REFERENCES "AspNetUsers" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_Approvals_PIApprover"
        FOREIGN KEY ("PIApproverUserId") REFERENCES "AspNetUsers" ("Id") ON DELETE RESTRICT
);

CREATE TABLE "tbl_Specimens" (
    "SpecimenID" integer GENERATED BY DEFAULT AS IDENTITY,
    "BarcodeID" varchar(100) NOT NULL,
    "LegacyID" varchar(100),
    "StudyID" integer,
    "SampleTypeID" integer,
    "CollectionDate" timestamp,
    "BoxID" integer,
    "PositionRow" integer,
    "PositionCol" integer,
    "RemainingSpots" integer,
    "SpotsShippedInternational" integer NOT NULL DEFAULT 0,
    "SpotsReservedLocal" integer NOT NULL DEFAULT 0,
    "AliquotNumber" integer,
    "DiscardApprovalID" integer,
    "Status" varchar(50) NOT NULL DEFAULT 'In-Stock',
    CONSTRAINT "PK_Specimens" PRIMARY KEY ("SpecimenID"),
    CONSTRAINT "UQ_Specimens_BarcodeID" UNIQUE ("BarcodeID"),
    CONSTRAINT "UQ_Specimens_BoxPosition" UNIQUE ("BoxID", "PositionRow", "PositionCol"),
    CONSTRAINT "CK_Specimens_Status" CHECK (
        "Status" IN ('In-Stock', 'Staged', 'Shipped', 'Missing', 'Depleted', 'Discarded', 'Temp', 'Not Yet Received')
    ),
    CONSTRAINT "CK_Specimens_AliquotNumber" CHECK (
        "AliquotNumber" IS NULL OR "AliquotNumber" IN (1, 2)
    ),
    CONSTRAINT "FK_Specimens_Studies"
        FOREIGN KEY ("StudyID") REFERENCES "tbl_Studies" ("StudyID") ON DELETE NO ACTION,
    CONSTRAINT "FK_Specimens_SampleTypes"
        FOREIGN KEY ("SampleTypeID") REFERENCES "tbl_SampleTypes" ("SampleTypeID") ON DELETE NO ACTION,
    CONSTRAINT "FK_Specimens_Boxes"
        FOREIGN KEY ("BoxID") REFERENCES "tbl_Boxes" ("BoxID") ON DELETE NO ACTION,
    CONSTRAINT "FK_Specimens_DiscardApproval"
        FOREIGN KEY ("DiscardApprovalID") REFERENCES "tbl_Approvals" ("ApprovalID") ON DELETE RESTRICT
);

CREATE TABLE "tbl_ShipmentBatches" (
    "BatchID" integer GENERATED BY DEFAULT AS IDENTITY,
    "ImportDate" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "ImportedByUserId" varchar(450),
    "RequestorName" varchar(100),
    "RequestorEmail" varchar(100),
    "TotalRequested" integer NOT NULL DEFAULT 0,
    "TotalAvailable" integer NOT NULL DEFAULT 0,
    "TotalNotFound" integer NOT NULL DEFAULT 0,
    "TotalPreviouslyShipped" integer NOT NULL DEFAULT 0,
    "TotalDiscarded" integer NOT NULL DEFAULT 0,
    "TotalNotYetReceived" integer NOT NULL DEFAULT 0,
    "ApprovalID" integer,
    "Status" varchar(50) NOT NULL DEFAULT 'Pending Approval',
    CONSTRAINT "PK_ShipmentBatches" PRIMARY KEY ("BatchID"),
    CONSTRAINT "CK_ShipmentBatches_Status" CHECK (
        "Status" IN ('Pending Approval', 'Approved', 'Rejected', 'Processing', 'Shipped')
    ),
    CONSTRAINT "FK_ShipmentBatches_ImportedBy"
        FOREIGN KEY ("ImportedByUserId") REFERENCES "AspNetUsers" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_ShipmentBatches_Approval"
        FOREIGN KEY ("ApprovalID") REFERENCES "tbl_Approvals" ("ApprovalID") ON DELETE RESTRICT
);

CREATE TABLE "tbl_ShipmentRequests" (
    "RequestID" integer GENERATED BY DEFAULT AS IDENTITY,
    "BatchID" integer,
    "RequestedBarcode" varchar(100) NOT NULL,
    "RequestedSampleTypeID" integer,
    "RequestorName" varchar(100),
    "RequestDate" timestamp,
    "MatchedSpecimenID" integer,
    "Status" varchar(50) NOT NULL DEFAULT 'Pending',
    CONSTRAINT "PK_ShipmentRequests" PRIMARY KEY ("RequestID"),
    CONSTRAINT "CK_ShipmentRequests_Status" CHECK (
        "Status" IN ('Pending', 'Staged', 'Shipped', 'Not Found', 'Previously Shipped', 'Discarded', 'Not Yet Received')
    ),
    CONSTRAINT "FK_ShipmentRequests_Batch"
        FOREIGN KEY ("BatchID") REFERENCES "tbl_ShipmentBatches" ("BatchID") ON DELETE RESTRICT,
    CONSTRAINT "FK_ShipmentRequests_SampleType"
        FOREIGN KEY ("RequestedSampleTypeID") REFERENCES "tbl_SampleTypes" ("SampleTypeID") ON DELETE RESTRICT,
    CONSTRAINT "FK_ShipmentRequests_Specimen"
        FOREIGN KEY ("MatchedSpecimenID") REFERENCES "tbl_Specimens" ("SpecimenID") ON DELETE RESTRICT
);

CREATE TABLE "tbl_Shipments" (
    "ShipmentID" integer GENERATED BY DEFAULT AS IDENTITY,
    "BatchID" integer,
    "ShipmentDate" timestamp NOT NULL,
    "Courier" varchar(100),
    "TrackingNumber" varchar(100),
    "DestinationAddress" varchar(255),
    "ShippedByUserId" varchar(450),
    "IsEntireBox" boolean NOT NULL DEFAULT false,
    "ShippedBoxID" integer,
    CONSTRAINT "PK_Shipments" PRIMARY KEY ("ShipmentID"),
    CONSTRAINT "FK_Shipments_Batch"
        FOREIGN KEY ("BatchID") REFERENCES "tbl_ShipmentBatches" ("BatchID") ON DELETE RESTRICT,
    CONSTRAINT "FK_Shipments_ShippedBy"
        FOREIGN KEY ("ShippedByUserId") REFERENCES "AspNetUsers" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_Shipments_ShippedBox"
        FOREIGN KEY ("ShippedBoxID") REFERENCES "tbl_Boxes" ("BoxID") ON DELETE RESTRICT
);

CREATE TABLE "tbl_ShipmentContents" (
    "ShipmentContentID" integer GENERATED BY DEFAULT AS IDENTITY,
    "ShipmentID" integer NOT NULL,
    "SpecimenID" integer NOT NULL,
    "ConditionAtShipment" varchar(100),
    "ShippingBoxPosition" varchar(20),
    "SpotsUsed" integer,
    CONSTRAINT "PK_ShipmentContents" PRIMARY KEY ("ShipmentContentID"),
    CONSTRAINT "FK_ShipmentContents_Shipment"
        FOREIGN KEY ("ShipmentID") REFERENCES "tbl_Shipments" ("ShipmentID") ON DELETE CASCADE,
    CONSTRAINT "FK_ShipmentContents_Specimen"
        FOREIGN KEY ("SpecimenID") REFERENCES "tbl_Specimens" ("SpecimenID") ON DELETE RESTRICT
);

CREATE TABLE "tbl_FilterPaperUsages" (
    "FilterPaperUsageID" integer GENERATED BY DEFAULT AS IDENTITY,
    "SpecimenID" integer NOT NULL,
    "UsageDate" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "SpotsUsed" integer NOT NULL,
    "IsInternationalShipment" boolean NOT NULL DEFAULT false,
    "UsedByUserId" varchar(450),
    "ShipmentContentID" integer,
    "Notes" text,
    CONSTRAINT "PK_FilterPaperUsages" PRIMARY KEY ("FilterPaperUsageID"),
    CONSTRAINT "CK_FilterPaperUsages_SpotsUsed" CHECK (
        "SpotsUsed" BETWEEN 1 AND 4
    ),
    CONSTRAINT "FK_FilterPaperUsages_Specimens"
        FOREIGN KEY ("SpecimenID") REFERENCES "tbl_Specimens" ("SpecimenID") ON DELETE CASCADE,
    CONSTRAINT "FK_FilterPaperUsages_UsedBy"
        FOREIGN KEY ("UsedByUserId") REFERENCES "AspNetUsers" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_FilterPaperUsages_ShipmentContent"
        FOREIGN KEY ("ShipmentContentID") REFERENCES "tbl_ShipmentContents" ("ShipmentContentID") ON DELETE SET NULL
);

CREATE TABLE "tbl_AuditLog" (
    "AuditLogID" integer GENERATED BY DEFAULT AS IDENTITY,
    "TableName" varchar(100) NOT NULL,
    "RecordID" integer NOT NULL,
    "FieldName" varchar(100) NOT NULL,
    "OldValue" text,
    "NewValue" text,
    "ChangedByUserId" varchar(450),
    "Timestamp" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "PK_AuditLog" PRIMARY KEY ("AuditLogID"),
    CONSTRAINT "FK_AuditLog_ChangedBy"
        FOREIGN KEY ("ChangedByUserId") REFERENCES "AspNetUsers" ("Id") ON DELETE RESTRICT
);

CREATE INDEX "IX_AuditLog_TableRecord" ON "tbl_AuditLog" ("TableName", "RecordID");
CREATE INDEX "IX_AuditLog_Timestamp" ON "tbl_AuditLog" ("Timestamp" DESC);

-- Seed Identity roles expected by Program.cs and the admin UI.
INSERT INTO "AspNetRoles" ("Id", "Name", "NormalizedName", "ConcurrencyStamp")
VALUES
    ('00000000-0000-0000-0000-000000000001', 'Admin', 'ADMIN', '10000000-0000-0000-0000-000000000001'),
    ('00000000-0000-0000-0000-000000000002', 'Write', 'WRITE', '10000000-0000-0000-0000-000000000002'),
    ('00000000-0000-0000-0000-000000000003', 'Read', 'READ', '10000000-0000-0000-0000-000000000003');

INSERT INTO "tbl_Studies" ("StudyCode", "StudyName", "PrincipalInvestigator")
VALUES
    ('PRISM', 'PRISM Study', 'Dr. Dorsey'),
    ('SAPPHIRE', 'SAPPHIRE Study', 'Dr. Jane'),
    ('PBO', 'PBO Study', 'Dr. Sam');

INSERT INTO "tbl_SampleTypes" ("TypeName", "IsConsumable", "MaxShippableUnits", "LocalReserveUnits")
VALUES
    ('Plasma', false, 1, 1),
    ('Buffy Coat', false, NULL, NULL),
    ('Whole Blood', false, NULL, NULL),
    ('Filter Paper', true, 2, 2);

INSERT INTO "tbl_Freezers" ("FreezerName", "Temperature", "LocationInBuilding")
VALUES
    ('-80 Freezer A', -80, 'Room 101'),
    ('-20 Freezer B', -20, 'Room 102');

INSERT INTO "tbl_Racks" ("RackName", "FreezerID")
VALUES
    ('Rack 1', 1),
    ('Rack 2', 1),
    ('Rack 3', 1),
    ('Rack 4', 1),
    ('Shelf 1', 2);

INSERT INTO "tbl_Boxes" ("BoxLabel", "BoxType", "BoxCategory", "RackID")
VALUES
    ('BOX-001', '81-slot', 'Standard', 1),
    ('BOX-002', '81-slot', 'Standard', 1),
    ('BOX-003', '100-slot', 'Standard', 2),
    ('FP-BINDER-01', 'Filter Paper Binder', 'Standard', 5),
    ('SYSTEM-TEMP', '100-slot', 'Temp', NULL),
    ('SYSTEM-TRASH', '100-slot', 'Trash', NULL),
    ('SYSTEM-SHIPPING', '100-slot', 'Shipping', NULL);

INSERT INTO "tbl_Specimens"
    ("BarcodeID", "StudyID", "SampleTypeID", "CollectionDate", "BoxID", "PositionRow", "PositionCol", "AliquotNumber")
SELECT
    'PLASMA-' || lpad(gs::text, 3, '0'),
    1,
    1,
    CURRENT_TIMESTAMP - make_interval(days => gs),
    1,
    ((gs - 1) / 9) + 1,
    ((gs - 1) % 9) + 1,
    CASE WHEN gs % 2 = 1 THEN 1 ELSE 2 END
FROM generate_series(1, 50) AS gs;

INSERT INTO "tbl_Specimens"
    ("BarcodeID", "StudyID", "SampleTypeID", "CollectionDate", "BoxID", "PositionRow", "PositionCol")
SELECT
    'BUFFY-' || lpad(gs::text, 3, '0'),
    2,
    2,
    CURRENT_TIMESTAMP - make_interval(days => gs),
    2,
    ((gs - 1) / 9) + 1,
    ((gs - 1) % 9) + 1
FROM generate_series(1, 35) AS gs;

INSERT INTO "tbl_Specimens"
    ("BarcodeID", "StudyID", "SampleTypeID", "CollectionDate", "BoxID", "PositionRow", "PositionCol")
SELECT
    'WB-' || lpad(gs::text, 3, '0'),
    1,
    3,
    CURRENT_TIMESTAMP - make_interval(days => gs),
    3,
    ((gs - 1) / 10) + 1,
    ((gs - 1) % 10) + 1
FROM generate_series(1, 30) AS gs;

INSERT INTO "tbl_Specimens"
    ("BarcodeID", "StudyID", "SampleTypeID", "CollectionDate", "BoxID", "PositionRow", "PositionCol", "RemainingSpots")
SELECT
    'FP-' || lpad(gs::text, 3, '0'),
    3,
    4,
    CURRENT_TIMESTAMP - make_interval(days => gs),
    4,
    gs,
    1,
    4
FROM generate_series(1, 25) AS gs;

COMMIT;
